class_name CharacterPartCatalog
extends Resource
## The player-facing set of selectable face/hair options, in display order.
## Index 0 of every list is the default part. Generated by
## tools/generate_character_resources.gd from the Blender manifest — do not
## hand-edit the generated .tres.

@export var hair: Array[CharacterPartDefinition] = []
@export var eyes: Array[CharacterPartDefinition] = []
@export var mouths: Array[CharacterPartDefinition] = []
@export var noses: Array[CharacterPartDefinition] = []


func options_for(slot: String) -> Array[CharacterPartDefinition]:
	match slot:
		CharacterSlots.HAIR:
			return hair
		CharacterSlots.EYES:
			return eyes
		CharacterSlots.MOUTH:
			return mouths
		CharacterSlots.NOSE:
			return noses
	return []


## The catalog part for a saved option index; out-of-range indices fall back
## to the default so old or damaged saves stay valid as the catalog evolves.
func part_for(slot: String, index: int) -> CharacterPartDefinition:
	var options := options_for(slot)
	if options.is_empty():
		return null
	if index < 0 or index >= options.size():
		return options[0]
	return options[index]


func display_names(slot: String) -> PackedStringArray:
	var names: PackedStringArray = []
	for part in options_for(slot):
		names.append(part.display_name if part != null else "?")
	return names
